# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.

version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1200
      runas: ec2-user

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 300
      runas: ec2-user
