version: '3'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/slack-clone-client
    ports:
      - "3000:3000"
    networks:
      - some-net    # load-balanced network


### which is a load-balanced overlay network
networks:
  some-net:
    driver: bridge