version: '3'
services:
  web:
    image: slack-clone-client
    restart: always
    build: .
    command: npm run start
    volumes:
      - .:/slack-clone-client
    ports:
      - "3000:3000"
    environment:
      REACT_APP_SECRET: efe
